In [41]:
import torch
from torch import nn

In [ ]:
bn = nn.BatchNorm2d( 2 )

In [31]:
x = torch.arange( 8.).reshape( 2,4 )
x

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [33]:
mean1 = x.mean( dim=0  )
var  = ( ( x - mean1 )**2 ).mean( dim=0 )
mean1, var

(tensor([2., 3., 4., 5.]), tensor([4., 4., 4., 4.]))

In [29]:
X_hat = (x - mean1) / torch.sqrt(var )
X_hat

tensor([[-1., -1., -1., -1.],
        [ 1.,  1.,  1.,  1.]])

In [38]:
x = torch.arange(16, dtype=torch.float32 ).reshape( 2,2 ,2,2 )
mean = x.mean(dim=(0 ,2,3), keepdim=True)
var = ((x - mean) ** 2).mean(dim=(0, 2, 3), keepdim=True)
x , mean , var 

(tensor([[[[ 0.,  1.],
           [ 2.,  3.]],
 
          [[ 4.,  5.],
           [ 6.,  7.]]],
 
 
         [[[ 8.,  9.],
           [10., 11.]],
 
          [[12., 13.],
           [14., 15.]]]]),
 tensor([[[[5.5000]],
 
          [[9.5000]]]]),
 tensor([[[[17.2500]],
 
          [[17.2500]]]]))

In [39]:
x_hat = (x - mean) / torch.sqrt(var )
x_hat

tensor([[[[-1.3242, -1.0835],
          [-0.8427, -0.6019]],

         [[-1.3242, -1.0835],
          [-0.8427, -0.6019]]],


        [[[ 0.6019,  0.8427],
          [ 1.0835,  1.3242]],

         [[ 0.6019,  0.8427],
          [ 1.0835,  1.3242]]]])

In [46]:
m = nn.BatchNorm2d(2)

BatchNorm2d(2, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)

In [49]:
input = torch.randn(20, 2, 35, 45)
input


tensor([[[[ 0.1924, -0.9532,  1.0574,  ...,  0.4176, -0.6950,  0.4081],
          [-0.7964, -2.1120, -1.3012,  ..., -0.2555,  1.0046,  1.3627],
          [ 0.6099, -0.1420, -0.3264,  ...,  0.1609, -0.5861,  0.0772],
          ...,
          [ 0.6437, -2.0141,  0.8126,  ...,  0.5952,  0.6301, -0.5663],
          [-0.2218, -0.2776,  0.4934,  ..., -0.3507,  0.8773, -0.3682],
          [-1.4554, -0.5714,  0.2896,  ...,  0.6541, -0.7719,  0.1435]],

         [[-0.5444, -0.9483,  0.0968,  ..., -1.0838,  0.1504, -1.3075],
          [-0.2286, -0.3277,  1.1877,  ..., -1.0918,  1.0547,  0.7912],
          [ 0.6196, -0.0586, -0.9293,  ..., -0.6561, -0.3266,  0.3031],
          ...,
          [-1.5545,  0.7278,  1.6812,  ...,  0.3597,  1.4394, -1.8363],
          [ 1.9261, -1.1124,  0.3634,  ...,  0.6323, -0.6135,  0.3899],
          [ 0.4591,  0.2113,  1.1020,  ..., -0.7412,  0.0714,  0.0404]]],


        [[[ 1.3640,  0.5953,  0.9840,  ...,  0.0435,  0.2116, -0.7052],
          [ 1.0059, -0.0422,

In [51]:
output = m(input)
output

tensor([[[[ 1.8902e-01, -9.6067e-01,  1.0571e+00,  ...,  4.1498e-01,
           -7.0155e-01,  4.0552e-01],
          [-8.0330e-01, -2.1235e+00, -1.3098e+00,  ..., -2.6050e-01,
            1.0041e+00,  1.3635e+00],
          [ 6.0795e-01, -1.4654e-01, -3.3165e-01,  ...,  1.5738e-01,
           -5.9221e-01,  7.3422e-02],
          ...,
          [ 6.4194e-01, -2.0253e+00,  8.1146e-01,  ...,  5.9320e-01,
            6.2827e-01, -5.7237e-01],
          [-2.2664e-01, -2.8260e-01,  4.9104e-01,  ..., -3.5600e-01,
            8.7638e-01, -3.7356e-01],
          [-1.4646e+00, -5.7747e-01,  2.8653e-01,  ...,  6.5240e-01,
           -7.7864e-01,  1.3999e-01]],

         [[-5.5283e-01, -9.5920e-01,  9.2247e-02,  ..., -1.0955e+00,
            1.4614e-01, -1.3205e+00],
          [-2.3515e-01, -3.3487e-01,  1.1898e+00,  ..., -1.1036e+00,
            1.0560e+00,  7.9083e-01],
          [ 6.1825e-01, -6.4049e-02, -9.4003e-01,  ..., -6.6518e-01,
           -3.3369e-01,  2.9984e-01],
          ...,
     