In [1]:
import torch
from d2l import torch as d2l

X, W_xh = torch.normal(0, 1, (3, 1)), torch.normal(0, 1, (1, 4))
H, W_hh = torch.normal(0, 1, (3, 4)), torch.normal(0, 1, (4, 4))
torch.matmul(X, W_xh) + torch.matmul(H, W_hh)


tensor([[-4.1561,  0.6031,  1.3389,  1.1928],
        [ 5.6737, -3.2015,  0.9152, -1.3683],
        [-2.5828, -2.5877,  4.4622,  2.9620]])

In [3]:
X, W_xh , H, W_hh

(tensor([[-0.1121],
         [ 0.0661],
         [-1.5134]]),
 tensor([[ 1.2567,  1.3578, -0.8243, -0.6825]]),
 tensor([[-0.5755,  0.3460,  0.7734, -1.2232],
         [ 0.3587,  1.2986, -1.7227, -0.0086],
         [ 0.2079,  1.4418,  1.6779, -1.0902]]),
 tensor([[ 1.7471,  0.0802,  1.3745,  1.0555],
         [ 2.3949, -1.6889,  0.7346, -0.4305],
         [-1.0884,  0.6577,  0.2835,  0.6689],
         [ 2.4497, -0.7172, -1.2787, -1.1081]]))

In [4]:
torch.cat( ( X,H ) , dim=1 ) , torch.cat( ( W_xh , W_hh ) , dim= 0 )

(tensor([[-0.1121, -0.5755,  0.3460,  0.7734, -1.2232],
         [ 0.0661,  0.3587,  1.2986, -1.7227, -0.0086],
         [-1.5134,  0.2079,  1.4418,  1.6779, -1.0902]]),
 tensor([[ 1.2567,  1.3578, -0.8243, -0.6825],
         [ 1.7471,  0.0802,  1.3745,  1.0555],
         [ 2.3949, -1.6889,  0.7346, -0.4305],
         [-1.0884,  0.6577,  0.2835,  0.6689],
         [ 2.4497, -0.7172, -1.2787, -1.1081]]))

In [5]:
torch.mm( torch.cat( ( X,H ) , dim=1 ) , torch.cat( ( W_xh , W_hh ) , dim= 0 ) )

tensor([[-4.1561,  0.6031,  1.3389,  1.1928],
        [ 5.6737, -3.2015,  0.9152, -1.3683],
        [-2.5828, -2.5877,  4.4622,  2.9620]])