In [71]:
import torch

In [72]:
torch.normal( 0,1 , size=( 10 , 1 ) ,requires_grad=True)

tensor([[ 0.0073],
        [ 1.4402],
        [ 0.8393],
        [-1.2547],
        [ 0.1243],
        [ 0.5344],
        [ 0.1138],
        [-0.7655],
        [ 0.4930],
        [-0.7074]], requires_grad=True)

* torch.no_grad()

In [73]:
a = torch.ones(2,requires_grad=True)
b = a*2


In [74]:
b.requires_grad

True

In [75]:
with torch.no_grad():
    b.mul_(2)#因为b.mul是inplace操作，所以在原地址对值进行了更改，但是无法对原属性requires_grad修改。而b=b*2相当于重新创建了一个对象b，所以在创建时不但可以改值，还可以将requires属性赋为false
    print( b.requires_grad )
b.requires_grad 

True


True

In [76]:
b.backward(torch.ones_like(b) ,retain_graph= True )

In [77]:
a.grad , b 

(tensor([2., 2.]), tensor([4., 4.], grad_fn=<MulBackward0>))

* torch.enable_grad

In [154]:
a = torch.ones(2,requires_grad=True)
b = a*2
print(a, a.grad, a.requires_grad )
b.sum().backward(retain_graph = True )
print(a, a.grad, a.requires_grad )
with torch.no_grad():
    a += a.grad
    print(a, a.grad, a.requires_grad )
    a.grad.zero_()
b.sum().backward(retain_graph = True )
print(a, a.grad ,a.requires_grad )

tensor([1., 1.], requires_grad=True) None True
tensor([1., 1.], requires_grad=True) tensor([2., 2.]) True
tensor([3., 3.], requires_grad=True) tensor([2., 2.]) True
tensor([3., 3.], requires_grad=True) tensor([2., 2.]) True


In [152]:
a = torch.ones(2,requires_grad=True)
b = a*2
print(a, a.grad, a.requires_grad )
b.sum().backward(retain_graph = True )
print(a, a.grad, a.requires_grad )
with torch.enable_grad():
    with torch.no_grad():
        a += a.grad
        print(a, a.grad, a.requires_grad )
        # a.grad.zero_()
b.sum().backward(retain_graph = True )
print(a, a.grad ,a.requires_grad )

tensor([1., 1.], requires_grad=True) None True
tensor([1., 1.], requires_grad=True) tensor([2., 2.]) True
tensor([3., 3.], requires_grad=True) tensor([2., 2.]) True
tensor([3., 3.], requires_grad=True) tensor([4., 4.]) True
