In [2]:
from d2l import torch as d2l
from torch.utils import data
import torch
from torch import nn

In [35]:
true_w = torch.tensor( [2 , -3.4])
true_b = torch.tensor( 4.2 )
features , labels = d2l.synthetic_data(true_w , true_b ,1000 )

In [36]:
def data_loader( data_array , batch_size , is_train=True ):
    dataset = data.TensorDataset( *data_array ) #返回一个dataset类，这个类就是每一个特征数据对应一个标签，可以用for a,b in dataset
                                                #进行打印
    return data.DataLoader( dataset , batch_size , shuffle = is_train )#Dataloader就像一个容器一样，将数据集载入后，我们可以自定
                                                                        #义如何取数据，这里的意思就是
                                                                        # 1.shuffle是True就代表迭起对象在每个迭代周期内允许打乱数据
                                                                        # 2.每次取batch_size个[特征,标签]个数据

In [37]:
batch_size = 10
data_iter = data_loader( (features , labels ) , batch_size )

In [38]:
next( iter( data_iter ))

[tensor([[ 1.2726,  0.0207],
         [ 0.5145, -0.0977],
         [-0.0664, -0.5774],
         [-1.1348, -0.5751],
         [ 2.1661,  1.5879],
         [-1.9877,  1.2320],
         [-0.1910, -0.1197],
         [ 1.5384, -0.3481],
         [-1.0090, -0.8144],
         [-0.7138, -0.5760]]),
 tensor([[ 6.6873],
         [ 5.5625],
         [ 6.0437],
         [ 3.8709],
         [ 3.1461],
         [-3.9624],
         [ 4.2259],
         [ 8.4581],
         [ 4.9583],
         [ 4.7274]])]

* 定义损失函数

In [39]:
loss = nn.MSELoss()

* 定义模型

In [40]:
model  = nn.Sequential( nn.Linear( 2 ,1 ))

* 定义优化器

In [41]:
trainer = torch.optim.SGD( model.parameters() , lr= 0.01 )

In [42]:
epochs = 10
for epoch in range( epochs ):
    for i , data in enumerate( data_iter , 1 ): #对应的数据从序号1开始
        x , y = data
        l = loss( model(x) , y )
        trainer.zero_grad()
        l.backward()
        trainer.step()
    print( f'epoch:{epoch} , loss:{l:f}')

epoch:0 , loss:0.832022
epoch:1 , loss:0.025330
epoch:2 , loss:0.000234
epoch:3 , loss:0.000049
epoch:4 , loss:0.000064
epoch:5 , loss:0.000100
epoch:6 , loss:0.000079
epoch:7 , loss:0.000033
epoch:8 , loss:0.000108
epoch:9 , loss:0.000080


In [47]:
predict_w , predict_b  = model[0].weight.data, model[0].bias.data
print( predict_w , predict_b )

tensor([[ 2.0000, -3.3996]]) tensor([4.1999])


In [50]:
model(torch.Tensor([ 1.2726,  0.0207] )) #结果正确

tensor([6.6747], grad_fn=<AddBackward0>)