In [1]:
import random
import torch
from d2l import torch as d2l

In [177]:
# 观察test_w是否是一个列向量
X = torch.arange(1,5,dtype=torch.float).reshape(2,2)
print(X , X.dtype )
test_w = torch.Tensor([[1.],[1.]])
result = torch.matmul( X , test_w )
print( result )
test_w.t()
#如果只有一个轴的向量就是列向量

tensor([[1., 2.],
        [3., 4.]]) torch.float32
tensor([[3.],
        [7.]])


tensor([[1., 1.]])

* **range应该是一个可迭代对象**

In [178]:
a = iter( range(10) )

In [179]:
next( a )

0

* **list能否对list直接做一个随机提取？**

In [180]:
# 随机取特征的单行数据，设置一个indics的指标进行随机选取
fetures = torch.arange(  1,5 ,dtype= torch.float ).reshape( 2 , 2)
print( fetures )
indics = [0,1]
random.shuffle(indics)
print( indics )
indics = torch.tensor( indics )
print( indics )
fetures , fetures[indics]

tensor([[1., 2.],
        [3., 4.]])
[1, 0]
tensor([1, 0])


(tensor([[1., 2.],
         [3., 4.]]),
 tensor([[3., 4.],
         [1., 2.]]))

In [181]:
test_one = [222,333 , 444 ]
indics_list = [ 0 , 1 ,2]
test_one[indics_list]

TypeError: list indices must be integers or slices, not list

In [ ]:
test_one = torch.tensor( [222,333 , 444 ] )
indics_list = torch.tensor( [ 0 , 1 ,2] )
test_one[indics_list]

**显然，由上下两段代码可知，list是不能由list进行提取，而tensor可以**

* **关于TensorDatasets和Dataloader**

In [190]:
from torch.utils.data import TensorDataset,DataLoader

In [201]:
a = torch.tensor([[11, 22, 33], [44, 55, 66], [77, 88, 99], [11, 22, 33], [44, 55, 66], [77, 88, 99], [11, 22, 33], [44, 55, 66], [77, 88, 99], [11, 22, 33], [44, 55, 66], [77, 88, 99]])
b = torch.tensor([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2])
train_ids = TensorDataset(a, b) 
print( train_ids[:5])
#所以TensorDataset就是将两个数据进行一个打包，往往是特征与对应的标签进行一个绑定

(tensor([[11, 22, 33],
        [44, 55, 66],
        [77, 88, 99],
        [11, 22, 33],
        [44, 55, 66]]), tensor([0, 1, 2, 0, 1]))


In [202]:
# 循环取数据
for train_data , train_laybers in train_ids:
    print( train_data , train_laybers)

tensor([11, 22, 33]) tensor(0)
tensor([44, 55, 66]) tensor(1)
tensor([77, 88, 99]) tensor(2)
tensor([11, 22, 33]) tensor(0)
tensor([44, 55, 66]) tensor(1)
tensor([77, 88, 99]) tensor(2)
tensor([11, 22, 33]) tensor(0)
tensor([44, 55, 66]) tensor(1)
tensor([77, 88, 99]) tensor(2)
tensor([11, 22, 33]) tensor(0)
tensor([44, 55, 66]) tensor(1)
tensor([77, 88, 99]) tensor(2)


In [203]:
train_loader = DataLoader(dataset=train_ids, batch_size=4)

In [204]:
next(  iter( train_loader ) )

[tensor([[11, 22, 33],
         [44, 55, 66],
         [77, 88, 99],
         [11, 22, 33]]),
 tensor([0, 1, 2, 0])]

* **观察1.4torch的normal是否仍然像numpy一样可用**

In [ ]:
torch.normal(0, 0.01,(2,1), requires_grad=True)#在1.1版本会报错

In [ ]:
x = torch.tensor([2., 1.], requires_grad=True)
y = torch.tensor([[1., 2.], [3., 4.]], requires_grad=True)

z = torch.mm(x.view(1, 2), y)
print(f"z:{z}")
z.backward(torch.Tensor([[1., 0]]))
print(f"x.grad: {x.grad}")
print(f"y.grad: {y.grad}")

In [ ]:
a = torch.tensor([1.1], requires_grad=True)
b = a * 2
b.backward()

In [ ]:
b.add_(2)
print(a.grad , a.grad_fn , b.grad , b.grad_fn )

In [ ]:
a = torch.tensor([1.1], requires_grad=True)
b = a * 2
b.requires_grad_()
b.backward(retain_graph=True)
print(b , a.grad,  b.grad_fn)
# with torch.no_grad():
#     a.add_(2)
b , a , a.grad , b.grad

In [ ]:
b.mul_(2)
b.backward(retain_graph=True)
print( a.grad , b.grad , b.grad_fn)#显然出现了梯度累加

In [ ]:
b.backward()

In [ ]:
b,b.grad

In [ ]:
X = torch.tensor( [1.] , requires_grad= True )
a = torch.add( X , 1 )**2
a.requires_grad_()
b = torch.add( X , 2 )

y = a * b
X , a , b , y 

In [ ]:
# y.backward()
print(a , a.grad , X.grad )

In [ ]:
w= torch.Tensor([1,1]).requires_grad_()
b= torch.Tensor([1]).requires_grad_()
w,b

In [ ]:
x = torch.ones( 2  , requires_grad= True ) 
# x.requires_grad_()
print(x.requires_grad)
y = torch.matmul(x , w) +b
y.sum().backward()
y , w.grad , x.grad , b.grad

* ** for a,b in list**

In [205]:
ls = [[1,2] , [3,4]]
for a, b in ls :
    print( a,b)

1 2
3 4


In [6]:
y = torch.tensor([0, 2])
y_hat = torch.tensor([[0.1, 0.3, 0.6], [0.3, 0.2, 0.5]])
y , y_hat,y_hat[[0, 1], y] #第一参数取到第0个元素[0.1, 0.3, 0.6]和第1个元素[0.3, 0.2, 0.5]，之后由y这个列表，对前面对应的元素一一对应
                           #取值，也就是说对0个元素取第0个值，对第1个元素取第2个值

(tensor([0, 2]),
 tensor([[0.1000, 0.3000, 0.6000],
         [0.3000, 0.2000, 0.5000]]),
 tensor([0.1000, 0.5000]))

In [7]:
y = torch.tensor([0, 2 ,0])
y_hat = torch.tensor([[0.1, 0.3, 0.6], [0.3, 0.2, 0.5]])
y , y_hat,y_hat[[0, 1], y] #显然多加了一个参数是出bug了，因为后一个列表与前一个列表的取值不匹配

IndexError: shape mismatch: indexing tensors could not be broadcast together with shapes [2], [3]

(1, 2, 3)
