* **测试torch.exp()**

In [8]:
import torch
from d2l import torch as d2l

In [9]:
x = torch.Tensor( [[ 1,2,3],[1,1,1]])
torch.exp(x)#显然这里是对每一个元素进行exp操作

tensor([[ 2.7183,  7.3891, 20.0855],
        [ 2.7183,  2.7183,  2.7183]])

* **softmax函数测试**

In [10]:
def softmax( x ):
    x_exp = torch.exp(x)
    partion = x_exp.sum(1 , keepdim = True )
    print( partion )
    return x_exp/partion #对输入进来的batch_size*10的数据进行exp操作，然后对每一行作sum操作得到一个batch_size的行向量
x = torch.Tensor([[1,2] , [1,4]] )
softmax( x ) , softmax( x ).sum(1)#这里很奇怪，axis设置为1才会对行进行计算

tensor([[10.1073],
        [57.3164]])
tensor([[10.1073],
        [57.3164]])


(tensor([[0.2689, 0.7311],
         [0.0474, 0.9526]]),
 tensor([1., 1.]))

* **损失函数测试**

In [11]:
def cross_entropy( y_hat , y):
    return - torch.log( y_hat[range(len( y_hat )) , y ])
y_hat = torch.Tensor( [[0.2,0.2,0.6], [ 0.01 , 0.98 , 0.01 ]] )
y = torch.tensor( [0, 1 ])
cross_entropy( y_hat , y)

tensor([1.6094, 0.0202])

* **测试torch.sum**

In [12]:
x= torch.Tensor([1,2])
x.sum(),x #sum方法不改变x本来的值，只是把这个值给返回掉

(tensor(3.), tensor([1., 2.]))

* **torch.type()函数测试**

In [13]:
x= torch.Tensor([1,2])
y = torch.tensor( [1,1])
print( x.dtype , y.dtype )
y.type( x.dtype )#注意：这样是没有办法对原来的数据类型进行修改的
print( x.dtype,y.dtype)
y = y.type( x.dtype )
print( y.dtype ) #这样的话就修改完毕

torch.float32 torch.int64
torch.float32 torch.int64
torch.float32


* **torch.argmax函数测试**

In [14]:
x= torch.Tensor([[8,2],[1,3],[8,9]])
x.argmax( dim =1 )#torch.argmax(dim)会返回dim维度上张量最大值的索引,并且原来的数据变成一维

tensor([0, 1, 1])

* **torch.size().numel()和torch.numel()的区别**

In [15]:
y = torch.tensor( [[ 1,2,3],[2,2,2]])
y.size().numel() , y.numel()#看不到区别，目前估计是一个装逼写法

(6, 6)

* **元组想加**

In [16]:
(1,2)+(1,)

(1, 2, 1)

In [17]:
from collections import Iterable,Iterator,Generator
a = (1,1)
isinstance( a , Iterable) , isinstance( a , Iterator ),  isinstance( a ,Generator)
#显然，元组也是一个与列表数据类型类似的可迭代对象

D:\CONDA\envs\d2l\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  """Entry point for launching an IPython kernel.


(True, False, False)

* **d2l.accuracy**

In [32]:
train_iter , _ = d2l.load_data_fashion_mnist( batch_size= 10 )
x,y = next( iter( train_iter ))

In [36]:
y_hat = torch.arange(10)
# d2l.accuracy( y_hat ,y)
# y_hat

In [41]:
def accruay( y_hat , y ):
    if len(y_hat.shape) > 1 and y_hat.shape[1] > 1:
        y_hat = torch.argmax( y_hat , dim=1 )#搞出每一行的的最大值
    count = y_hat.type( y.dtype ) == y 
    return float( count.type( y.dtype).sum())
accruay( y_hat,y )

1.0

## **list相加**

In [45]:
l = [1,2,3]
l.sum()#列表是没有sum方法的

AttributeError: 'list' object has no attribute 'sum'

In [46]:
l = [1,2,3]
sum(l)#但是我们可以使用sum函数进行求和

6